project_id = "qolvoivjbkyyxfrixpob"

[auth]
enabled = true
# The base URL of your website. Used as an allow-list for redirects and for constructing URLs used
# in emails.
site_url = "http://127.0.0.1:8080"
# A list of *exact* URLs that auth providers are permitted to redirect to post authentication.
additional_redirect_urls = ["http://localhost:8080", "http://localhost:8080/auth/callback"]

[auth.external.google]
enabled = true
client_id ="env(GOOGLE_CLIENT)"
secret ="env(GOOGLE_SECRET)"
redirect_uri = "http://localhost:54321/auth/v1/callback"

# TODO(PROD): Uncomment verify_jwt = true once CLI/runtime supports it
# verify_jwt = true

# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
