project_id = "qolvoivjbkyyxfrixpob"

[auth]
enabled = true
# The base URL of your website. Used as an allow-list for redirects and for constructing URLs used
# in emails.
site_url = "http://127.0.0.1:8080"
# A list of *exact* URLs that auth providers are permitted to redirect to post authentication.
additional_redirect_urls = ["http://localhost:8080", "http://localhost:8080/auth/callback"]

[auth.external.google]
enabled = true
client_id ="env(GOOGLE_CLIENT)"
secret ="env(GOOGLE_SECRET)"
redirect_uri = "http://localhost:54321/auth/v1/callback"
[functions.get-conversations2]
enabled = true
verify_jwt = true
import_map = "./functions/get-conversations2/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/get-conversations2/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/get-conversations2/*.html" ]
