// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qolvoivjbkyyxfrixpob.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFvbHZvaXZqYmt5eXhmcml4cG9iIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMzMTg5ODEsImV4cCI6MjA1ODg5NDk4MX0.f4b4_6SmOE6V9n1URHrHJoZjxa7X17IyRHlo95DzFvI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);